# Generated by Django 5.2.16 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='receive_promotions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
