# Generated by Django 5.2.16 on 2026-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_ref_id_patientprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='supplementary_insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
