# Generated by Django 5.2.16 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='key',
            field=models.CharField(choices=[('appointment_reminder', 'یادآوری نوبت'), ('new_message', 'پیام جدید'), ('prescription_ready', 'نسخه آماده'), ('marketing', 'اخبار و تخفیف\u200cها'), ('weekly_report', 'گزارش هفتگی سلامت')], max_length=30),
        ),
    ]
