# Generated by Django 5.2.16 on 2026-08-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_supportthread_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, upload_to='chat_voice/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'متن'), ('prescription', 'نسخه'), ('system', 'سیستمی'), ('file', 'فایل'), ('voice', 'صوتی')], default='text', max_length=12),
        ),
    ]
