# Generated by Django 5.2.16 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending-payment', 'در انتظار پرداخت'), ('pending-approval', 'در انتظار تأیید'), ('waiting', 'در انتظار'), ('in-progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending-payment', max_length=16),
        ),
    ]
