# Generated by Django 5.2.16 on 2026-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
