# Generated by Django 5.2.16 on 2026-07-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('approved', 'تأیید'), ('pending', 'در انتظار'), ('suspended', 'معلق')], default='pending', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='admin_panel.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('license', 'مجوز فعالیت'), ('national_id', 'کارت ملی'), ('experience', 'سوابق کار'), ('specialty', 'تخصص'), ('profile_photo', 'عکس پروفایل'), ('other', 'سایر')], max_length=20)),
                ('file', models.FileField(upload_to='doctor_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'doctor_documents',
            },
        ),
        migrations.CreateModel(
            name='CommunicationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_enabled', models.BooleanField(default=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('chat_fee', models.PositiveIntegerField(default=100000)),
                ('audio_fee', models.PositiveIntegerField(default=150000)),
                ('video_fee', models.PositiveIntegerField(default=250000)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comm_settings', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'communication_settings',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه')], max_length=12)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='doctors.doctorprofile')),
            ],
            options={
                'db_table': 'working_hours',
                'unique_together': {('doctor', 'day')},
            },
        ),
    ]
