# Generated by Django 5.2.16 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghour',
            options={'ordering': ('day', 'from_time')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=19),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='shaba',
            field=models.CharField(blank=True, max_length=26),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='workinghour',
            constraint=models.UniqueConstraint(fields=('doctor', 'day', 'from_time', 'to_time'), name='unique_doctor_working_slot'),
        ),
    ]
