# Generated by Django 5.2.16 on 2026-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_workinghour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsetting',
            name='chat_auto_close_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='appointment_duration_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
