# Generated by Django 5.2.16 on 2026-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_communicationsetting_chat_auto_close_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='prefix',
            field=models.CharField(blank=True, default='دکتر', max_length=20),
        ),
    ]
