# Generated by Django 5.2.16 on 2026-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_add_prefix_insurance_defs'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='supplementary_insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
