# Generated by Django 5.2.16 on 2026-07-27 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'drug_suggestions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('setting_type', models.CharField(choices=[('text', 'متن'), ('number', 'عدد'), ('toggle', 'تغییر وضعیت'), ('select', 'انتخاب')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('welcome', 'خوش آمدگویی'), ('appointment_confirmation', 'تأیید نوبت'), ('appointment_reminder', 'یادآوری نوبت'), ('prescription_ready', 'نسخه آماده'), ('withdrawal_approved', 'برداشت تأیید'), ('withdrawal_rejected', 'برداشت رد')], max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_templates',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'تخصص\u200cها',
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید'), ('rejected', 'رد')], default='pending', max_length=10)),
                ('bank_info', models.CharField(blank=True, max_length=255)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'بروزرسانی'), ('delete', 'حذف'), ('approve', 'تأیید'), ('reject', 'رد'), ('suspend', 'تعلیق'), ('unsuspend', 'رفع تعلیق'), ('verify', 'تأیید مدارک'), ('login', 'ورود'), ('logout', 'خروج'), ('export', 'خروجی'), ('settings_change', 'تغییر تنظیمات')], max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('diagnosis', 'تشخیص'), ('allergy', 'آلرژی'), ('drug', 'دارو'), ('city', 'شهر'), ('gender', 'جنسیت'), ('blood_type', 'گروه خونی'), ('marital_status', 'وضعیت تأهل')], max_length=15)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'definitions',
                'unique_together': {('type', 'name')},
            },
        ),
    ]
