# Generated by Django 5.2.16 on 2026-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='type',
            field=models.CharField(choices=[('diagnosis', 'تشخیص'), ('allergy', 'آلرژی'), ('drug', 'دارو'), ('city', 'شهر'), ('gender', 'جنسیت'), ('blood_type', 'گروه خونی'), ('marital_status', 'وضعیت تأهل'), ('insurance_type', 'نوع بیمه درمانی'), ('supplementary_insurance', 'بیمه تکمیلی')], max_length=30),
        ),
    ]
