# Generated by Django 5.2.16 on 2026-07-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('card_number', models.CharField(blank=True, max_length=16)),
                ('card_hash', models.CharField(blank=True, max_length=64)),
                ('tracking_code', models.CharField(blank=True, max_length=20)),
                ('ref_id', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='appointments.appointment')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
